plugins {
    id 'java'
}

group = 'com.fallen'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.11.4')
    testImplementation (
            "com.codeborne:selenide:6.19.1",
            'org.junit.jupiter:junit-jupiter',
            'com.github.javafaker:javafaker:1.0.2'
    )
}

test {
    useJUnitPlatform()
}